# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('new_password', models.CharField(max_length=300)),
                ('confirm_password', models.CharField(max_length=300)),
                ('birthday', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
